### ISSUE TITLE
Start Break

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#17]
How does the subject start their break?

Do we add a third button to the button box?
If yes, the third button will bring the main loop to a stand still till the button is pressed again (`waitkeys`) and wait for this key to restart

**Comment by zora-no** [comment]
Comments from Anna on Slack:

What you want is that the next block only starts after both participants gave their go (or during the mandatory breaks the experimenter has to start the next block). This means: After a block it says sth like "You finished one block. Press right to continue." or "You finished one block. Wait for the experimenter to start the next blocl. "

And for the experimenter this could be space or any other button.
Of course this could mean that one subject wants to continue, but the other one not. But so be it. Maybe we need an indication screen that both participants want to continue now, so that no one is caught of guard. (edited) 

Never have the experiment on auto-mode so that it will continue if nothing is pressed :wink:

Also, each block will take on average 8min (max of 11.3 min), which is long but doable.
