### ISSUE TITLE
Counterbalance mapping between button press and choice across subjects

### ISSUE THREAD

**Issue by frbosse** [104H/dyadicdecisionmaking#23]
Subjects will report their choice by pressing one of two response buttons with the middle or index finger. The mapping between button press and choice (e.g., lower button, yes; and upper button, no) should be counterbalanced across subjects to avoid biased data since the index finger is in general faster than the middle finger. 
Anna suggested to change the mapping based on the pair id, i.e. all pairs with an even number use mapping 1 (lower button, yes; and upper button, no) and all pairs with an odd number use mapping 2 (lower button, no; and upper button, yes).

**Comment by 104H** [comment]
Will the experiment will have an attribute ‘yesfinger’ which will define which finger was used and that will be recorded along with the rest of data (?) And this attribute can be set with the sys args (?)


Sent from a mobile device, please excuse brevity.

On 13. May 2021, at 10:04 AM, frbosse ***@***.***> wrote:

﻿

Subjects will report their choice by pressing one of two response buttons with the middle or index finger. The mapping between button press and choice (e.g., lower button, yes; and upper button, no) should be counterbalanced across subjects to avoid biased data since the index finger is in general faster than the middle finger.
Anna suggested to change the mapping based on the pair id, i.e. all pairs with an even number use mapping 1 (lower button, yes; and upper button, no) and all pairs with an odd number use mapping 2 (lower button, no; and upper button, yes).

**Comment by frbosse** [comment]
This is something we have to decide. We can add an attribute that tracks the mapping of the fingers in the data. Even if we don't need this information in the end, it does not hurt to have it. For the other point we can either set it with the sys args or use Anna's simple approach and check for even and odd pair numbers. What is more preferable?

**Comment by zora-no** [comment]
we can easily add that via the experiment handler, i also think it doesn't hurt to have it.
i think checking for even/ odd pair numbers is preferable because the less the we manually need to input the better since it leaves less room for mistakes.

**Comment by 104H** [comment]
Agreed. The even/odd solution is much easier.

Regards
Hunaid

Sent from a mobile device, please excuse brevity.

On 15. May 2021, at 4:21 PM, zora-no ***@***.***> wrote:

﻿

we can easily add that via the experiment handler, i also think it doesn't hurt to have it.
i think checking for even/ odd pair numbers is preferable because the less the we manually need to input the better since it leaves less room for mistakes.

**Comment by zora-no** [comment]
Franca solved this with commit `774b46c2d85d354ffcbc52339c566235a855fa6d`
