### ISSUE TITLE
specify 2 keyboards: one for each participant

### ISSUE THREAD

**Issue by zora-no** [104H/dyadicdecisionmaking#43]
https://www.psychopy.org/api/hardware/keyboard.html

Introducing the keyboard module allow us to specify one input device (i.e. button box) for each participant, which makes the input check Hunaid implemented redundant.

**Comment by 104H** [comment]
List of changes:

1. Make a button box object for each subject, using the keyboard id of their button box
2. in fetch button press, first identify acting subject, then look for input on their keyboard object
3. no need to clear buffers before hand, since there is no risk of having left over input in the buffer from the other subject

please add

**Comment by zora-no** [comment]
4. adjust getacknowledgments()
5. adjust getexperimenterack()

**Comment by 104H** [comment]
7. discontinue use of global variable rt and return the response time as the return value

**Comment by zora-no** [comment]
That can be treated as a separate issue as this issue is irrelevant for it.

**Comment by 104H** [comment]
> pygame doesn’t return timestamps (they are always 0)
https://www.psychopy.org/api/hardware/keyboard.html#psychopy.hardware.keyboard.getKeyboards

Might need to change the backend from pygame to something else too

**Comment by zora-no** [comment]
> 3. no need to clear buffers before hand, since there is no risk of having left over input in the buffer from the other subject

We should still clear the buffers in case they press some buttons by accident or something.

**Comment by zora-no** [comment]
I have prepared the code for 2., 4., 5.

Let me know when you're ready with 1. and 6.
